# Generated by Django 5.2.3 on 2025-06-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='zAuHz3jWyFgbH8ZrPpUhSDkhamOIzyjX', editable=False, max_length=32, unique=True),
        ),
    ]
