# Generated by Django 5.2.3 on 2025-06-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
