# Generated by Django 5.2.3 on 2025-07-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
