# Generated by Django 5.2.3 on 2025-07-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expo_notification_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
